version: '2'
services:
    dlfinancialcontrol-app:
        image: dlfinancialcontrol
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dlfinancialcontrol-mysql:3306/dlfinancialcontrol?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dlfinancialcontrol-elasticsearch:9300
        ports:
            - 8080:8080
    dlfinancialcontrol-mysql:
        extends:
            file: mysql.yml
            service: dlfinancialcontrol-mysql
    dlfinancialcontrol-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dlfinancialcontrol-elasticsearch
